-- Combat showcase configurations. Native DF owns every action and outcome.
return {
    platform={title='The ledge assault',left={race='DWARF',count=8,weapon='AXE_BATTLE',skill='AXE',level=16,armor='full',material='STEEL',
        roles={{weapon='CROSSBOW',skill='CROSSBOW',ranged=true},{weapon='CROSSBOW',skill='CROSSBOW',ranged=true},{weapon='CROSSBOW',skill='CROSSBOW',ranged=true},{weapon='SPEAR',skill='SPEAR'},{weapon='HAMMER_WAR',skill='HAMMER'}}},
        right={race='GOBLIN',count=25,weapon='SWORD_SHORT',skill='SWORD',level=12,armor='light',material='COPPER',
        roles={[1]={weapon='BOW',skill='BOW',ranged=true,ammo='ARROWS'},[5]={weapon='BOW',skill='BOW',ranged=true,ammo='ARROWS'},[9]={weapon='BOW',skill='BOW',ranged=true,ammo='ARROWS'},[13]={weapon='BOW',skill='BOW',ranged=true,ammo='ARROWS'},[17]={weapon='BOW',skill='BOW',ranged=true,ammo='ARROWS'},[21]={weapon='BOW',skill='BOW',ranged=true,ammo='ARROWS'},[25]={race='OGRE',weapon=false,skill='WRESTLING',armor='none'}}},
        layout='platform',width=31,height=31,capture_width=1920,capture_height=1080,camera_pitch=-0.6,camera_distance=27,orbit_close_distance=20,camera_focus_height=1.8,capture_seconds=50,orbit_seconds=45,show_fps=true,
        equipment_note='Eight mixed defenders on a rough three-level platform; eighteen goblin climbers, six archers and an ogre',team_labels={left='Platform defenders',right='Goblin assault'}},
    hill={title='King of the hill',left={race='DWARF',count=8,weapon='AXE_BATTLE',skill='AXE',level=16,armor='full',material='STEEL'},
        right={race='GOBLIN',count=60,weapon='SWORD_SHORT',skill='SWORD',level=5,armor='light',material='COPPER',
            varied_weapons={{'SWORD_SHORT','SWORD'},{'AXE_BATTLE','AXE'},{'SPEAR','SPEAR'},{'HAMMER_WAR','HAMMER'}}},
        layout='hill',width=49,height=49,camera_distance=43,orbit_close_distance=31,camera_focus_height=2.2,capture_seconds=50,orbit_seconds=45,show_fps=true,
        equipment_note='Eight steel-armored dwarves hold a three-level hill against sixty goblins',team_labels={left='Hill defenders',right='Goblin swarm'}},
    unarmed={title='Close quarters',left={race='DWARF',count=2,skill='WRESTLING',level=12},
        right={race='GOBLIN',count=3,skill='WRESTLING',level=8},layout='open',width=13,height=11,camera_distance=12,capture_seconds=20,
        equipment_note='Unarmed dwarves and goblins',team_labels={left='Dwarves',right='Goblins'}},
    skirmish={title='Three dwarves versus six goblins',left={race='DWARF',count=3,weapon='SWORD_SHORT',skill='SWORD',level=10,armor='full',material='IRON'},
        right={race='GOBLIN',count=6,weapon='SWORD_SHORT',skill='SWORD',level=8,armor='medium',material='IRON'},layout='open',width=15,height=13,camera_distance=15,capture_seconds=25,
        equipment_note='Iron-armored dwarves against six goblins',team_labels={left='Dwarves',right='Goblins'}},
    gate={title='Hold the breach',left={race='DWARF',count=3,weapon='AXE_BATTLE',skill='AXE',level=14,armor='full',material='STEEL'},
        right={race='GOBLIN',count=20,weapon='SWORD_SHORT',skill='SWORD',level=5,armor='light',material='COPPER',
            varied_weapons={{'SWORD_SHORT','SWORD'},{'AXE_BATTLE','AXE'},{'SPEAR','SPEAR'},{'HAMMER_WAR','HAMMER'}}},layout='gate',width=29,height=19,camera_distance=22,capture_seconds=35,
        equipment_note='Three steel-armored axedwarves face twenty goblins',team_labels={left='Axedwarves',right='Goblins'}},
    crossbows={title='Volley at the pillars',left={race='DWARF',count=6,weapon='CROSSBOW',skill='CROSSBOW',level=14,armor='medium',material='STEEL',ranged=true},
        right={race='JABBERER',count=1,level=10},layout='cover',width=33,height=21,camera_distance=20,capture_seconds=30,
        equipment_note='Six crossbow dwarves, steel bolts, and stone cover',team_labels={left='Crossbow dwarves',right='Jabberer'}},
    dragon={title='Spears against scales',left={race='DWARF',count=5,weapon='SPEAR',skill='SPEAR',level=14,armor='full',material='STEEL'},
        right={race='CAVE_DRAGON',count=1,level=12},layout='open',width=29,height=21,camera_distance=16,capture_seconds=30,
        equipment_note='Five armored speardwarves confront a cave dragon',team_labels={left='Speardwarves',right='Cave dragon'}},
    monsters={title='Ancient predators',left={race='CRETACEOUS_TYRANNOSAURUS',count=1,level=12},
        right={race='VORACIOUS_CAVE_CRAWLER',count=1,level=12},layout='open',width=31,height=23,camera_distance=16,capture_seconds=30,
        equipment_note='Tyrannosaurus versus voracious cave crawler',team_labels={left='Tyrannosaurus',right='Cave crawler'}},
}
