// Generated by tools/generate_management_contract.py. Do not edit.
#pragma once
#include <cstdint>
namespace wm {
enum class ManagementAction : uint8_t {
  Catalog = 0,
  Preview = 1,
  Place = 2,
  Inspect = 3,
  Remove = 4,
  InspectAtTile = 5,
  RemoveConstruction = 6,
  AreaCatalog = 7,
  AreaInspectAtTile = 8,
  AreaInspect = 9,
  AreaCreate = 10,
  AreaUpdate = 11,
  AreaDelete = 12,
  AreaLink = 13,
  AreaCandidates = 14,
  ProductionList = 15,
  ProductionInspect = 16,
  ProductionQueue = 17,
  ProductionJobEdit = 18,
  FarmSetCrop = 19,
  WorkOrderList = 20,
  WorkOrderInspect = 21,
  WorkOrderCreate = 22,
  WorkOrderUpdate = 23,
  WorkOrderDelete = 24,
  WorkOrderCondition = 25,
  WorkOrderCandidates = 26,
  WorkOrderCatalog = 27,
  CitizenList = 28,
  CitizenInspect = 29,
  WorkDetailList = 30,
  WorkDetailInspect = 31,
  WorkDetailMembership = 32,
  WorkDetailMode = 33,
  ReportList = 34,
  ReportInspect = 35,
  AgreementList = 36,
  AgreementInspect = 37,
  TradeList = 38,
  TradeInspect = 39,
  TradeUpdate = 40,
  TradeGoods = 41,
  TradeBring = 42,
  TradeExchangeOpen = 43,
  TradeExchangeInspect = 44,
  TradeExchangeSelect = 45,
  TradeExchangeSubmit = 46,
  TradeExchangeClose = 47,
  StocksOpen = 48,
  StocksList = 49,
  StocksInspect = 50,
  StocksClose = 51,
  AppointmentsOpen = 52,
  AppointmentsCandidates = 53,
  AppointmentsAssign = 54,
  AppointmentsBack = 55,
  KitchenOpen = 56,
  KitchenList = 57,
  KitchenSetPermission = 58,
  KitchenClose = 59,
  Alert = 60,
  Selection = 61,
  CreatureInspect = 62,
  ConstructionMaterials = 63,
  WorkDetailCreate = 64,
  WorkDetailDelete = 65,
  WorkDetailEdit = 66,
  CitizenWorkScope = 67,
};
enum class ManagementStatus : uint8_t {
  Idle = 0,
  Pending = 1,
  Ok = 2,
  Rejected = 3,
};
enum class AreaKind : uint8_t {
  Stockpile = 0,
  Zone = 1,
  Workshop = 2,
};
enum class AreaOperation : uint8_t {
  None = 0,
  SettingsPage = 1,
  SettingsSet = 2,
  Preset = 3,
  Rename = 4,
  Paint = 5,
  LocationList = 6,
  LocationSet = 7,
  LocationCreate = 8,
  ZoneSettings = 9,
  Links = 10,
  AssignUnits = 11,
  SquadUse = 12,
  Toggles = 13,
  CandidateList = 14,
  WorkshopLink = 15,
};
enum class AlertOperation : uint8_t {
  OpenCategory = 0,
  Inspect = 1,
  OpenUnit = 2,
  Recenter = 3,
  Back = 4,
  Dismiss = 5,
  OpenHistory = 6,
  SelectTab = 7,
  Scroll = 8,
};
enum class AlertView : uint8_t {
  Closed = 0,
  Category = 1,
  Unit = 2,
  History = 3,
};
enum class SelectionOperation : uint8_t {
  OpenTile = 0,
  Inspect = 1,
  SelectAlternative = 2,
  InspectItem = 3,
  ViewContainer = 4,
  Back = 5,
};
enum class SelectionKind : uint8_t {
  None = 0,
  Unit = 1,
  Item = 2,
  Building = 3,
  Engraving = 4,
  PlannedEngraving = 5,
  UnitList = 6,
  ItemList = 7,
  Vermin = 8,
};
enum class SelectionSection : uint8_t {
  AgeSex = 0,
  Traits = 1,
  Health = 2,
  Citizenship = 3,
  Military = 4,
  CurrentThought = 5,
  RecentThoughts = 6,
  Relationships = 7,
  Hauling = 8,
  LaborSkills = 9,
  UnmetNeeds = 10,
};
enum class CreatureSectionKind : uint8_t {
  Identity = 0,
  Skills = 1,
  Attributes = 2,
  Health = 3,
  Inventory = 4,
  Relationships = 5,
  Personality = 6,
  Values = 7,
  Needs = 8,
  Dreams = 9,
  Emotions = 10,
  Preferences = 11,
  Military = 12,
  Labors = 13,
  Rooms = 14,
  Groups = 15,
  Memories = 16,
  Treatment = 17,
  HealthHistory = 18,
  Knowledge = 19,
  Uniform = 20,
  Kills = 21,
  Workshops = 22,
  Locations = 23,
  WorkAnimals = 24,
};
constexpr bool isRuntimeAction(ManagementAction action) {
  switch (action) {
  case ManagementAction::Catalog: return true;
  case ManagementAction::Preview: return true;
  case ManagementAction::Place: return true;
  case ManagementAction::Inspect: return true;
  case ManagementAction::Remove: return true;
  case ManagementAction::InspectAtTile: return true;
  case ManagementAction::RemoveConstruction: return true;
  case ManagementAction::AreaCatalog: return true;
  case ManagementAction::AreaInspectAtTile: return true;
  case ManagementAction::AreaInspect: return true;
  case ManagementAction::AreaCreate: return true;
  case ManagementAction::AreaUpdate: return true;
  case ManagementAction::AreaDelete: return true;
  case ManagementAction::AreaLink: return true;
  case ManagementAction::AreaCandidates: return true;
  case ManagementAction::ProductionList: return true;
  case ManagementAction::ProductionInspect: return true;
  case ManagementAction::ProductionQueue: return true;
  case ManagementAction::ProductionJobEdit: return true;
  case ManagementAction::FarmSetCrop: return true;
  case ManagementAction::WorkOrderList: return true;
  case ManagementAction::WorkOrderInspect: return true;
  case ManagementAction::WorkOrderCreate: return true;
  case ManagementAction::WorkOrderUpdate: return true;
  case ManagementAction::WorkOrderDelete: return true;
  case ManagementAction::WorkOrderCondition: return true;
  case ManagementAction::WorkOrderCandidates: return true;
  case ManagementAction::WorkOrderCatalog: return true;
  case ManagementAction::CitizenList: return true;
  case ManagementAction::CitizenInspect: return true;
  case ManagementAction::WorkDetailList: return true;
  case ManagementAction::WorkDetailInspect: return true;
  case ManagementAction::WorkDetailMembership: return true;
  case ManagementAction::WorkDetailMode: return true;
  case ManagementAction::ReportList: return true;
  case ManagementAction::ReportInspect: return true;
  case ManagementAction::AgreementList: return true;
  case ManagementAction::AgreementInspect: return true;
  case ManagementAction::TradeList: return true;
  case ManagementAction::TradeInspect: return true;
  case ManagementAction::TradeUpdate: return true;
  case ManagementAction::TradeGoods: return true;
  case ManagementAction::TradeBring: return true;
  case ManagementAction::CreatureInspect: return true;
  case ManagementAction::ConstructionMaterials: return true;
  case ManagementAction::WorkDetailCreate: return true;
  case ManagementAction::WorkDetailDelete: return true;
  case ManagementAction::WorkDetailEdit: return true;
  case ManagementAction::CitizenWorkScope: return true;
  default: return false;
  }
}
constexpr const char* managementDomain(ManagementAction action) {
  switch (action) {
  case ManagementAction::Catalog: return "construction";
  case ManagementAction::Preview: return "construction";
  case ManagementAction::Place: return "construction";
  case ManagementAction::Inspect: return "construction";
  case ManagementAction::Remove: return "construction";
  case ManagementAction::InspectAtTile: return "construction";
  case ManagementAction::RemoveConstruction: return "construction";
  case ManagementAction::ConstructionMaterials: return "construction";
  case ManagementAction::AreaCatalog: return "areas";
  case ManagementAction::AreaInspectAtTile: return "areas";
  case ManagementAction::AreaInspect: return "areas";
  case ManagementAction::AreaCreate: return "areas";
  case ManagementAction::AreaUpdate: return "areas";
  case ManagementAction::AreaDelete: return "areas";
  case ManagementAction::AreaLink: return "areas";
  case ManagementAction::AreaCandidates: return "areas";
  case ManagementAction::ProductionList: return "production";
  case ManagementAction::ProductionInspect: return "production";
  case ManagementAction::ProductionQueue: return "production";
  case ManagementAction::ProductionJobEdit: return "production";
  case ManagementAction::FarmSetCrop: return "production";
  case ManagementAction::WorkOrderList: return "work_orders";
  case ManagementAction::WorkOrderInspect: return "work_orders";
  case ManagementAction::WorkOrderCreate: return "work_orders";
  case ManagementAction::WorkOrderUpdate: return "work_orders";
  case ManagementAction::WorkOrderDelete: return "work_orders";
  case ManagementAction::WorkOrderCondition: return "work_orders";
  case ManagementAction::WorkOrderCandidates: return "work_orders";
  case ManagementAction::WorkOrderCatalog: return "work_orders";
  case ManagementAction::CitizenList: return "citizens";
  case ManagementAction::CitizenInspect: return "citizens";
  case ManagementAction::WorkDetailList: return "citizens";
  case ManagementAction::WorkDetailInspect: return "citizens";
  case ManagementAction::WorkDetailMembership: return "citizens";
  case ManagementAction::WorkDetailMode: return "citizens";
  case ManagementAction::WorkDetailCreate: return "citizens";
  case ManagementAction::WorkDetailDelete: return "citizens";
  case ManagementAction::WorkDetailEdit: return "citizens";
  case ManagementAction::CitizenWorkScope: return "citizens";
  case ManagementAction::ReportList: return "reports";
  case ManagementAction::ReportInspect: return "reports";
  case ManagementAction::AgreementList: return "agreements";
  case ManagementAction::AgreementInspect: return "agreements";
  case ManagementAction::TradeList: return "trade";
  case ManagementAction::TradeInspect: return "trade";
  case ManagementAction::TradeUpdate: return "trade";
  case ManagementAction::TradeGoods: return "trade";
  case ManagementAction::TradeBring: return "trade";
  default: return "";
  }
}
} // namespace wm
