# Generated by tools/generate_management_contract.py. Do not edit.
extends RefCounted
enum ManagementAction {
	Catalog = 0,
	Preview = 1,
	Place = 2,
	Inspect = 3,
	Remove = 4,
	InspectAtTile = 5,
	RemoveConstruction = 6,
	AreaCatalog = 7,
	AreaInspectAtTile = 8,
	AreaInspect = 9,
	AreaCreate = 10,
	AreaUpdate = 11,
	AreaDelete = 12,
	AreaLink = 13,
	AreaCandidates = 14,
	ProductionList = 15,
	ProductionInspect = 16,
	ProductionQueue = 17,
	ProductionJobEdit = 18,
	FarmSetCrop = 19,
	WorkOrderList = 20,
	WorkOrderInspect = 21,
	WorkOrderCreate = 22,
	WorkOrderUpdate = 23,
	WorkOrderDelete = 24,
	WorkOrderCondition = 25,
	WorkOrderCandidates = 26,
	WorkOrderCatalog = 27,
	CitizenList = 28,
	CitizenInspect = 29,
	WorkDetailList = 30,
	WorkDetailInspect = 31,
	WorkDetailMembership = 32,
	WorkDetailMode = 33,
	ReportList = 34,
	ReportInspect = 35,
	AgreementList = 36,
	AgreementInspect = 37,
	TradeList = 38,
	TradeInspect = 39,
	TradeUpdate = 40,
	TradeGoods = 41,
	TradeBring = 42,
	TradeExchangeOpen = 43,
	TradeExchangeInspect = 44,
	TradeExchangeSelect = 45,
	TradeExchangeSubmit = 46,
	TradeExchangeClose = 47,
	StocksOpen = 48,
	StocksList = 49,
	StocksInspect = 50,
	StocksClose = 51,
	AppointmentsOpen = 52,
	AppointmentsCandidates = 53,
	AppointmentsAssign = 54,
	AppointmentsBack = 55,
	KitchenOpen = 56,
	KitchenList = 57,
	KitchenSetPermission = 58,
	KitchenClose = 59,
	Alert = 60,
	Selection = 61,
	CreatureInspect = 62,
	ConstructionMaterials = 63,
	WorkDetailCreate = 64,
	WorkDetailDelete = 65,
	WorkDetailEdit = 66,
	CitizenWorkScope = 67,
}
enum ManagementStatus {
	Idle = 0,
	Pending = 1,
	Ok = 2,
	Rejected = 3,
}
enum AreaKind {
	Stockpile = 0,
	Zone = 1,
	Workshop = 2,
}
enum AreaOperation {
	None = 0,
	SettingsPage = 1,
	SettingsSet = 2,
	Preset = 3,
	Rename = 4,
	Paint = 5,
	LocationList = 6,
	LocationSet = 7,
	LocationCreate = 8,
	ZoneSettings = 9,
	Links = 10,
	AssignUnits = 11,
	SquadUse = 12,
	Toggles = 13,
	CandidateList = 14,
	WorkshopLink = 15,
}
enum AlertOperation {
	OpenCategory = 0,
	Inspect = 1,
	OpenUnit = 2,
	Recenter = 3,
	Back = 4,
	Dismiss = 5,
	OpenHistory = 6,
	SelectTab = 7,
	Scroll = 8,
}
enum AlertView {
	Closed = 0,
	Category = 1,
	Unit = 2,
	History = 3,
}
enum SelectionOperation {
	OpenTile = 0,
	Inspect = 1,
	SelectAlternative = 2,
	InspectItem = 3,
	ViewContainer = 4,
	Back = 5,
}
enum SelectionKind {
	None = 0,
	Unit = 1,
	Item = 2,
	Building = 3,
	Engraving = 4,
	PlannedEngraving = 5,
	UnitList = 6,
	ItemList = 7,
	Vermin = 8,
}
enum SelectionSection {
	AgeSex = 0,
	Traits = 1,
	Health = 2,
	Citizenship = 3,
	Military = 4,
	CurrentThought = 5,
	RecentThoughts = 6,
	Relationships = 7,
	Hauling = 8,
	LaborSkills = 9,
	UnmetNeeds = 10,
}
enum CreatureSectionKind {
	Identity = 0,
	Skills = 1,
	Attributes = 2,
	Health = 3,
	Inventory = 4,
	Relationships = 5,
	Personality = 6,
	Values = 7,
	Needs = 8,
	Dreams = 9,
	Emotions = 10,
	Preferences = 11,
	Military = 12,
	Labors = 13,
	Rooms = 14,
	Groups = 15,
	Memories = 16,
	Treatment = 17,
	HealthHistory = 18,
	Knowledge = 19,
	Uniform = 20,
	Kills = 21,
	Workshops = 22,
	Locations = 23,
	WorkAnimals = 24,
}

static func domain_of(action: int) -> String:
	match action:
		ManagementAction.Catalog, ManagementAction.Preview, ManagementAction.Place, ManagementAction.Inspect, ManagementAction.Remove, ManagementAction.InspectAtTile, ManagementAction.RemoveConstruction, ManagementAction.ConstructionMaterials: return "construction"
		ManagementAction.AreaCatalog, ManagementAction.AreaInspectAtTile, ManagementAction.AreaInspect, ManagementAction.AreaCreate, ManagementAction.AreaUpdate, ManagementAction.AreaDelete, ManagementAction.AreaLink, ManagementAction.AreaCandidates: return "areas"
		ManagementAction.ProductionList, ManagementAction.ProductionInspect, ManagementAction.ProductionQueue, ManagementAction.ProductionJobEdit, ManagementAction.FarmSetCrop: return "production"
		ManagementAction.WorkOrderList, ManagementAction.WorkOrderInspect, ManagementAction.WorkOrderCreate, ManagementAction.WorkOrderUpdate, ManagementAction.WorkOrderDelete, ManagementAction.WorkOrderCondition, ManagementAction.WorkOrderCandidates, ManagementAction.WorkOrderCatalog: return "work_orders"
		ManagementAction.CitizenList, ManagementAction.CitizenInspect, ManagementAction.WorkDetailList, ManagementAction.WorkDetailInspect, ManagementAction.WorkDetailMembership, ManagementAction.WorkDetailMode, ManagementAction.WorkDetailCreate, ManagementAction.WorkDetailDelete, ManagementAction.WorkDetailEdit, ManagementAction.CitizenWorkScope: return "citizens"
		ManagementAction.ReportList, ManagementAction.ReportInspect: return "reports"
		ManagementAction.AgreementList, ManagementAction.AgreementInspect: return "agreements"
		ManagementAction.TradeList, ManagementAction.TradeInspect, ManagementAction.TradeUpdate, ManagementAction.TradeGoods, ManagementAction.TradeBring: return "trade"
	return ""

static func is_runtime(action: int) -> bool:
	return action in [ManagementAction.Catalog, ManagementAction.Preview, ManagementAction.Place, ManagementAction.Inspect, ManagementAction.Remove, ManagementAction.InspectAtTile, ManagementAction.RemoveConstruction, ManagementAction.AreaCatalog, ManagementAction.AreaInspectAtTile, ManagementAction.AreaInspect, ManagementAction.AreaCreate, ManagementAction.AreaUpdate, ManagementAction.AreaDelete, ManagementAction.AreaLink, ManagementAction.AreaCandidates, ManagementAction.ProductionList, ManagementAction.ProductionInspect, ManagementAction.ProductionQueue, ManagementAction.ProductionJobEdit, ManagementAction.FarmSetCrop, ManagementAction.WorkOrderList, ManagementAction.WorkOrderInspect, ManagementAction.WorkOrderCreate, ManagementAction.WorkOrderUpdate, ManagementAction.WorkOrderDelete, ManagementAction.WorkOrderCondition, ManagementAction.WorkOrderCandidates, ManagementAction.WorkOrderCatalog, ManagementAction.CitizenList, ManagementAction.CitizenInspect, ManagementAction.WorkDetailList, ManagementAction.WorkDetailInspect, ManagementAction.WorkDetailMembership, ManagementAction.WorkDetailMode, ManagementAction.ReportList, ManagementAction.ReportInspect, ManagementAction.AgreementList, ManagementAction.AgreementInspect, ManagementAction.TradeList, ManagementAction.TradeInspect, ManagementAction.TradeUpdate, ManagementAction.TradeGoods, ManagementAction.TradeBring, ManagementAction.CreatureInspect, ManagementAction.ConstructionMaterials, ManagementAction.WorkDetailCreate, ManagementAction.WorkDetailDelete, ManagementAction.WorkDetailEdit, ManagementAction.CitizenWorkScope]

static func is_mutation(action: int) -> bool:
	return action in [ManagementAction.Place, ManagementAction.Remove, ManagementAction.RemoveConstruction, ManagementAction.AreaCreate, ManagementAction.AreaUpdate, ManagementAction.AreaDelete, ManagementAction.AreaLink, ManagementAction.ProductionQueue, ManagementAction.ProductionJobEdit, ManagementAction.FarmSetCrop, ManagementAction.WorkOrderCreate, ManagementAction.WorkOrderUpdate, ManagementAction.WorkOrderDelete, ManagementAction.WorkOrderCondition, ManagementAction.WorkDetailMembership, ManagementAction.WorkDetailMode, ManagementAction.WorkDetailCreate, ManagementAction.WorkDetailDelete, ManagementAction.WorkDetailEdit, ManagementAction.CitizenWorkScope, ManagementAction.TradeUpdate, ManagementAction.TradeBring]
