extends "res://tests/area_settings_controller_test.gd"

func links_reply(rows: Array, cursor := 0, receipt := 91) -> void:
	reply(9,{"area":{"links":rows,"list_revision":receipt,"build_phase":3,
		"build_done":4,"build_total":4,"next_cursor":cursor}})

func run() -> void:
	world = Base.FakeWorld.new()
	var list_state = preload("res://scripts/area_locations_state.gd").new()
	var list_reads: Array=[]
	list_state.request_ready.connect(func(request): list_reads.append(request))
	list_state.open({"id":23,"kind":1,"revision":17})
	list_state.accept({"list_revision":99,"locations":[{"id":1}],"next_cursor":128},list_reads[-1])
	check(list_reads.size()==2 and list_reads[-1].cursor==128 and list_reads[-1].expected_list_revision==99,"Location list follows the complete immutable receipt")
	list_state.assign(1)
	check(list_reads.size()==2 and list_state.busy(),"Partial location list cannot assign")
	list_state.accept({"list_revision":99,"locations":[{"id":2}],"next_cursor":0},list_reads[-1])
	check(not list_state.busy() and list_state.rows.size()==2,"Location list becomes selectable after final page")
	var interaction := Base.FakeInteraction.new(); root.add_child(interaction)
	service = preload("res://scripts/semantic_action_service.gd").new()
	service.configure(world); root.add_child(service); service.set_process(false)
	var host = preload("res://scripts/ui_host.gd").new(); host.interaction = interaction; root.add_child(host)
	controller = preload("res://scripts/areas.gd").new()
	controller.world = world; controller.action_service = service; controller.ui_host = host; controller.interaction = interaction
	root.add_child(controller); host.register(controller); controller.set_process(false)
	controller.open_panel(); service.poll(); reply(0); reply(7)
	var pile := {"id":39,"revision":9007199254740993,"kind":0,"name":"Wood Stockpile #39",
		"origin":Vector3i(3,4,2),"width":2,"height":2,"extents":PackedByteArray([1,1,1,1]),
		"tile_count":4,"categories":8192,"barrels":0,"bins":0,"wheelbarrows":0,"links_only":false,
		"active":true,"owner_id":-1,"owner_name":"","owner_allowed":false,"gives":[],"takes":[]}
	controller.use_area(pile); controller.stockpile_control("links"); service.poll()
	check(world.calls[-1].operation == 10 and world.calls[-1].expected_revision == pile.revision,"links read keeps exact source revision")
	reply(9,{"area":{"list_revision":0,"build_done":1,"build_total":4}})
	var count: int = world.calls.size()
	controller._process(0.249); service.poll()
	check(world.calls.size() == count,"pending links build waits before polling")
	controller._process(0.001); service.poll()
	check(world.calls.size() == count + 1,"pending links build polls at 250ms")
	var first := {"id":40,"kind":0,"direction":1,"name":"Stone Stockpile #40"}
	var second := {"id":50,"kind":2,"direction":2,"name":"Carpenter's Workshop"}
	links_reply([first],1)
	controller.links_view.more_requested.emit(); service.poll()
	check(world.calls[-1].cursor == 1 and world.calls[-1].expected_list_revision == 91,"next links page uses receipt")
	links_reply([second])
	check(controller.observed_links == [first,second],"completed phase three pages retain observed names and directions")
	controller.links_view.rows_box.get_child(1).get_child(2).pressed.emit(); service.poll()
	var sent: Dictionary = world.calls[-1]
	check(sent.action == 13 and sent.operation == 15 and sent.id == 50 and sent.link_id == 39 and sent.give and sent.unlink and sent.expected_revision == pile.revision,"workshop unlink reverses direction and keeps pile revision")
	reply(13,{"areas":[pile]}); service.poll(); links_reply([first])
	check(controller.stockpile_page == "links" and controller.selected.id == 39,"mutation refresh preserves source and links page")
	controller.begin_link_pick(true); controller.link_target_tile(Vector3i(5,4,2)); service.poll()
	reply(8,{"areas":[{"id":40,"kind":0}],"area_next_cursor":0}); service.poll()
	sent = world.calls[-1]
	check(sent.action == 13 and sent.id == 39 and sent.link_id == 40 and sent.give and not sent.unlink,"map stockpile pick edits original source")
	reply(13,{"areas":[pile]}); service.poll(); links_reply([first])
	controller.begin_link_pick(false); controller.link_target_tile(Vector3i(8,4,2)); service.poll()
	reply(8,{"areas":[],"area_next_cursor":0}); service.poll()
	check(world.calls[-1].action == 5 and world.calls[-1].origin == Vector3i(8,4,2),"empty area pick inspects building at same tile")
	reply(5,{"building_id":50}); service.poll()
	sent = world.calls[-1]
	check(sent.operation == 15 and sent.id == 50 and sent.link_id == 39 and sent.give,"take from workshop is workshop give to pile")
	reply(13,{"areas":[pile]}); service.poll(); links_reply([first])
	controller.begin_link_pick(true); controller.link_target_tile(Vector3i(5,4,2)); service.poll()
	count = world.calls.size(); controller.handle_back()
	reply(8,{"areas":[{"id":40,"kind":0}],"area_next_cursor":0}); service.poll()
	check(world.calls.size() == count and not controller.links_picking and controller.selected.id == 39,"cancel ignores late map pick without mutation")
	controller.links_view.rows_box.get_child(0).get_child(2).pressed.emit()
	var back_ticket: int = controller.request_ticket
	controller.handle_back(); service.poll()
	check(world.calls.size() == count and service.result(back_ticket).get("outcome","") == "not_sent" and controller.stockpile_page == "types","Done cancels queued unlink when leaving links page")
	controller.stockpile_control("links"); service.poll(); links_reply([first],1)
	controller.links_view.more_requested.emit(); service.poll(); links_reply([second],0,92)
	check(controller.observed_links == [first] and controller.request_problem,"changed receipt cannot append mismatched links")
	count = world.calls.size()
	controller.links_view.rows_box.get_child(0).get_child(2).pressed.emit()
	var ticket: int = controller.request_ticket
	controller.close_panel(); service.poll()
	check(world.calls.size() == count and service.result(ticket).get("outcome","") == "not_sent","close cancels queued unlink before dispatch")
	controller.open_panel(); service.poll(); reply(0); reply(7)
	controller.use_area(pile); controller.stockpile_control("repaint")
	controller.paint_pointer(Vector3i(5,4,2),true); controller.paint_motion(Vector3i(8,4,2))
	check(controller.paint_state.cells.size() == 4 and controller.paint_preview.mesh != null and controller.paint_view.accept_button.disabled,"rectangle hover previews without modifying draft or permitting Accept")
	controller.handle_back(); controller.stockpile_control("repaint")
	controller.paint_pointer(Vector3i(5,4,2),true); controller.paint_pointer(Vector3i(5,4,2),false)
	controller.paint_pointer(Vector3i(5,4,2),true); controller.paint_pointer(Vector3i(5,4,2),false)
	controller.paint_view.buttons.erase.pressed.emit()
	controller.paint_pointer(Vector3i(3,4,2),true); controller.paint_pointer(Vector3i(3,4,2),false)
	controller.paint_pointer(Vector3i(3,4,2),true); controller.paint_pointer(Vector3i(3,4,2),false)
	check(controller.paint_view.visible and controller.paint_state.cells.size() == 4,"connected repaint draft combines add and erase")
	controller.paint_view.accept_button.pressed.emit(); service.poll()
	sent = world.calls[-1]
	check(sent.action == 11 and sent.operation == 5 and sent.paint_mode == 3 and sent.expected_revision == pile.revision and sent.spans.size() == 2,"Accept sends one exact-revision replacement")
	count = world.calls.size()
	var changed := pile.duplicate(true); changed.revision += 1
	changed.width = 3; changed.extents = PackedByteArray([0,1,1,1,1,0])
	reply(11,{"areas":[changed]}); service.poll()
	check(world.calls.size() == count and controller.mode == "inspect" and controller.selected.revision == changed.revision,"paint success observes result without another mutation")
	controller.stockpile_control("repaint")
	controller.paint_pointer(Vector3i(6,4,2),true); controller.paint_pointer(Vector3i(6,4,2),false)
	controller.paint_pointer(Vector3i(6,4,2),true); controller.paint_pointer(Vector3i(6,4,2),false)
	controller.paint_view.accept_button.pressed.emit(); ticket = controller.request_ticket
	controller.handle_back(); service.poll()
	check(world.calls.size() == count and service.result(ticket).get("outcome","") == "not_sent" and controller.paint_state.cells.is_empty(),"cancel paint detaches queued mutation and discards draft")
	controller.stockpile_control("repaint"); controller.paint_view.buttons.brush.pressed.emit()
	controller.paint_pointer(Vector3i(7,7,2),true); controller.paint_motion(Vector3i(12,7,2))
	controller.paint_pointer(Vector3i(12,7,2),false)
	for x in range(7,13): check(controller.paint_state.cells.has(Vector2i(x,7)),"connected brush fills skipped pointer samples")
	controller.paint_pointer(Vector3i(13,7,2),true)
	var release := InputEventMouseButton.new(); release.button_index = MOUSE_BUTTON_LEFT
	release.pressed = false; release.position = controller.panel.get_global_rect().get_center()
	controller._input(release)
	check(not controller.dragging and controller.rectangle.has_area() and controller.paint_state.cells.has(Vector2i(12,7)),"release over panel cancels stroke without losing earlier draft or outline basis")
	controller.handle_back()
	controller.new_area()
	check(controller.mode == "paint" and controller.selected.is_empty() and controller.paint_view.buttons.remove.disabled,"new pile opens native painter with remove unavailable")
	controller.map_paint_pointer(Vector3i(3,4,2),true); service.poll()
	controller.map_paint_pointer(Vector3i(3,4,2),false)
	reply(8,{"areas":[pile],"area_next_cursor":0})
	check(controller.selected.id == 39 and controller.mode == "inspect" and controller.paint_state.cells.is_empty(),"initial map click selects existing pile even after release")
	controller.new_area()
	controller.map_paint_pointer(Vector3i(10,1,2),true); service.poll()
	controller.paint_motion(Vector3i(12,3,2)); controller.map_paint_pointer(Vector3i(12,3,2),false)
	check(controller.paint_view.accept_button.disabled,"provisional paint cannot be accepted before lookup")
	reply(8,{"areas":[{"id":80,"kind":1}],"area_next_cursor":5}); service.poll()
	check(world.calls[-1].cursor == 5 and world.calls[-1].origin == Vector3i(10,1,2),"zone overlap continues lookup on original press tile")
	reply(8,{"areas":[],"area_next_cursor":0})
	check(controller.paint_state.cells.size() == 9 and not controller.paint_view.accept_button.disabled,"empty lookup preserves completed drag instead of dropping release")
	controller.new_area()
	controller.map_paint_pointer(Vector3i(3,4,2),true); service.poll(); controller.handle_back()
	reply(8,{"areas":[pile],"area_next_cursor":0})
	check(controller.selected.is_empty() and controller.paint_state.cells.is_empty(),"cancelled lookup cannot select late pile")
	controller.paint_pointer(Vector3i(10,1,2),true); controller.paint_pointer(Vector3i(29,10,2),false)
	controller.paint_view.accept_button.pressed.emit(); service.poll()
	sent = world.calls[-1]
	check(sent.action == 10 and sent.operation == 5 and sent.paint_mode == 1 and sent.spans.size() == 10 and not sent.has("categories") and not sent.has("expected_revision"),"new pile sends only one native-default create intent")
	var created := pile.duplicate(true); created.id = 71; created.categories = 0
	reply(10,{"areas":[created]})
	check(controller.selected.id == 71 and controller.stockpile_view.visible and controller.mode == "inspect","create observes native identity and opens type panel")
	controller.new_area(); controller.paint_pointer(Vector3i(10,1,2),true); controller.paint_pointer(Vector3i(11,2,2),false)
	controller.handle_back()
	check(controller.panel.visible and controller.paint_state.cells.is_empty(),"first Back clears new draft without closing mode")
	controller.handle_back(); check(not controller.panel.visible,"second Back closes empty new painter")
	controller.set_area_kind(1); controller.open_panel(); service.poll(); reply(0); reply(7,{"area_choices":[{"id":0,"name":"Bedroom"}]})
	controller.inspect_tile(Vector3i(3,4,2)); service.poll()
	check(controller.zone_menu.visible and controller.selected.is_empty(),"zone chooser remains visible during inspection")
	reply(8,{"areas":[pile],"area_next_cursor":81}); service.poll()
	check(world.calls[-1].action == 8 and world.calls[-1].cursor == 81 and world.calls[-1].origin == Vector3i(3,4,2),"stockpile-only page continues zone lookup on same tile")
	var zone: Dictionary = pile.duplicate(true)
	zone.id = 82; zone.kind = 1; zone.zone_type = 0; zone.zone_label = "Bedroom"; zone.name = "Unnamed bedroom"
	reply(8,{"areas":[pile,zone],"area_next_cursor":0})
	check(controller.selected.id == 82 and controller.launcher_destination == "Zones" and world.zone_overlays,"mixed overlap selects zone without changing launcher or overlays")
	check(controller.areas.size() == 1 and controller.areas[0].kind == 1,"zone overlap choices omit stockpiles")
	controller.new_area(); controller.inspect_tile(Vector3i(3,4,2)); service.poll()
	var second_zone: Dictionary = zone.duplicate(true); second_zone.id = 90; second_zone.revision = 0
	var third_zone: Dictionary = zone.duplicate(true); third_zone.id = 91; third_zone.revision = 0
	reply(8,{"areas":[zone],"area_next_cursor":90}); service.poll()
	check(controller.selected.is_empty() and world.calls[-1].cursor == 90,"zone lookup reads remaining pages before choosing last overlap")
	reply(8,{"areas":[second_zone,third_zone],"area_next_cursor":0}); service.poll()
	check(controller.selected.id == 91 and world.calls[-1].action == 9 and world.calls[-1].id == 91,"initial overlap selection inspects last observed native identity")
	check(controller.zone_menu.controls.previous.disabled,"overlap arrows disabled during selected-zone inspection")
	third_zone.revision = 130; reply(9,{"areas":[third_zone]})
	check(controller.zone_overlaps.size() == 3 and controller.zone_menu.controls.previous.visible,"inspection keeps complete overlap navigation")
	controller.zone_menu.controls.previous.pressed.emit(); service.poll()
	check(world.calls[-1].action == 9 and world.calls[-1].id == 90,"previous arrow performs fresh semantic inspection")
	second_zone.revision = 131; reply(9,{"areas":[second_zone]})
	controller.zone_menu.controls.next.pressed.emit(); service.poll(); reply(9,{"areas":[third_zone]})
	controller.zone_menu.controls.next.pressed.emit(); service.poll()
	check(world.calls[-1].id == 82,"next arrow wraps from last to first overlap")
	reply(9,{"areas":[zone]})
	controller.zone_menu.controls.previous.pressed.emit(); service.poll()
	check(world.calls[-1].id == 91,"previous arrow wraps from first to last overlap")
	reply(9,{"areas":[third_zone]})
	controller.inspect_tile(Vector3i(3,4,2)); service.poll()
	reply(8,{"areas":[zone,second_zone,third_zone],"area_next_cursor":0})
	check(controller.selected.id == 91,"repeated map click retains selected overlap")
	controller.new_area()
	zone.owner_allowed = true; zone.owner_id = 17; controller.use_area(zone)
	controller.zone_menu.controls.owner.pressed.emit(); service.poll()
	check(controller.candidates_view.visible and controller.zone_menu.visible and world.calls[-1].operation == 14,"owner button opens native selector and enriched read")
	reply(14,{"area":{"list_revision":91,"build_phase":3,"candidates":[{"id":21,"name":"Urist","profession":"Miner","sex":1,"mood":3}]}})
	var focused: Array = []; controller.focus_requested.connect(func(tile): focused.append(tile))
	world.unit_tiles[21] = Vector3i(5,6,2); controller.candidates_view.refresh()
	count = world.calls.size(); controller.candidates_view.focus_buttons[0].pressed.emit()
	check(focused == [Vector3i(5,6,2)] and world.calls.size() == count and controller.candidates_view.visible,"recenter uses observed unit location without assigning or closing selector")
	world.unit_tiles.clear(); controller.candidates_view.focus_buttons[0].pressed.emit()
	check(focused.size() == 1,"recenter revalidates vanished unit at click time")
	controller.candidates_view.focus_unit(999)
	check(focused.size() == 1,"unlisted unit cannot be recentered from stale callback")
	controller.candidates_view.search.text = "New"
	controller.candidates_view.search.text_changed.emit("New")
	controller._process(0.25); service.poll()
	check(world.calls[-1].query == "New" and controller.candidates_view.search.editable,"connected owner search stays editable while pending")
	controller.handle_back(); reply(14,{"area":{"list_revision":92,"candidates":[{"id":99,"name":"Late"}]}})
	check(not controller.candidates_view.visible and controller.candidates_state.rows.is_empty() and controller.selected.id == zone.id,"selector Back preserves zone and rejects late rows")
	controller.zone_menu.controls.owner.pressed.emit(); service.poll()
	reply(14,{"area":{"list_revision":93,"candidates":[{"id":21,"name":"Urist","profession":"Miner","sex":1,"mood":3}]}})
	controller.candidates_view.choices[0].pressed.emit(); service.poll()
	check(world.calls[-1].owner_id == 21 and world.calls[-1].expected_revision == zone.revision and controller.selected.owner_id == 17,"row click sends exact owner edit without optimistic state")
	zone.owner_id = 21; zone.owner_name = "Urist"; zone.revision += 1
	reply(11,{"areas":[zone]})
	check(controller.selected.owner_id == 21 and not controller.candidates_view.visible,"assignment reply returns to observed zone panel")
	controller.zone_menu.controls.owner.pressed.emit(); service.poll()
	reply(14,{"area":{"list_revision":94,"candidates":[{"id":22,"name":"New owner"}]}})
	controller.candidates_view.choices[0].pressed.emit()
	var owner_ticket: int = controller.request_ticket; count = world.calls.size()
	controller.handle_back(); service.poll()
	check(world.calls.size() == count and service.result(owner_ticket).get("outcome","") == "not_sent","Back cancels queued owner mutation before dispatch")
	check(controller.selected.owner_id == 21 and not controller.candidates_view.visible,"cancelled owner mutation preserves observed assignment")
	var settings_cases := [["Pond","pond_mode",1,2],["ArcheryRange","facing",2,3],["Tomb","tomb_citizens",1,0],["Tomb","tomb_pets",0,1],["PlantGathering","gather_trees",1,0],["PlantGathering","gather_shrubs",0,1]]
	for index in settings_cases.size():
		var item: Array = settings_cases[index]
		var typed: Dictionary = zone.duplicate(true)
		typed.zone_type = 100+index; typed.zone_settings = {item[1]:item[2]}
		for definition in controller.menu_data.zones:
			if definition.name == item[0]:
				var observed: Dictionary = definition.duplicate(true); observed.id = typed.zone_type
				controller.zone_types.append(observed)
		controller.use_area(typed)
		check(controller.zone_menu.visible,"native per-type panel shown for " + str(item[0]))
		for button_index in controller.zone_menu.SETTINGS.size():
			var definition: Array = controller.zone_menu.SETTINGS[button_index]
			if definition[0] == item[0] and definition[1] == item[1] and (int(definition[2]) < 0 or definition[2] == item[3]):
				controller.zone_menu.setting_buttons[button_index].pressed.emit()
		service.poll()
		check(world.calls[-1] == {"action":11,"id":typed.id,"kind":1,"expected_revision":typed.revision,"operation":9,"zone_settings":{item[1]:item[3]}},"per-type edit sends one field with exact revision")
		check(controller.selected.zone_settings[item[1]] == item[2],"per-type state remains authoritative while pending")
		count = world.calls.size(); controller.set_zone_setting(item[1],item[3]); service.poll()
		check(world.calls.size() == count,"pending setting cannot duplicate mutation")
		typed.zone_settings[item[1]] = item[3]; typed.revision += 1
		reply(11,{"areas":[typed]})
		check(controller.selected.zone_settings[item[1]] == item[3],"setting reply updates observed controls")
	var pen: Dictionary = zone.duplicate(true); pen.zone_type = 200; pen.owner_allowed = false; pen.zone_label = "Pen/Pasture"
	for definition in controller.menu_data.zones:
		if definition.name == "Pen":
			var observed: Dictionary = definition.duplicate(true); observed.id = 200; controller.zone_types.append(observed)
	controller.use_area(pen); controller.zone_menu.controls.animals.pressed.emit(); service.poll()
	check(world.calls[-1].candidate_kind == 2 and controller.candidates_view.visible,"animal icon opens enriched animal selector")
	reply(14,{"area":{"list_revision":101,"candidates":[{"id":24,"name":"Goat","assigned":false,"grazer":true}]}})
	check(not controller.candidates_view.remove.visible,"animal selector has no owner-removal row")
	controller.candidates_view.choices[0].pressed.emit(); service.poll()
	check(world.calls[-1].operation == 11 and world.calls[-1].unit_id == 24 and world.calls[-1].assign == 1,"animal row sends assignment")
	pen.revision += 1; reply(11,{"areas":[pen]}); service.poll()
	check(controller.stockpile_page == "animals" and controller.candidates_view.visible and world.calls[-1].candidate_kind == 2,"assignment preserves animal selector and refreshes observed list")
	reply(14,{"area":{"list_revision":102,"candidates":[{"id":24,"name":"Goat","assigned":true,"grazer":true}]}})
	controller.candidates_view.choices[0].pressed.emit(); service.poll()
	check(world.calls[-1].assign == 0 and world.calls[-1].expected_revision == pen.revision,"second animal click unassigns using new zone revision")
	pen.revision += 1; reply(11,{"areas":[pen]}); service.poll()
	controller.handle_back(); reply(14,{"area":{"list_revision":103,"candidates":[]}})
	check(not controller.candidates_view.visible and controller.candidates_state.rows.is_empty(),"animal Back rejects late refresh")
	var barracks: Dictionary = zone.duplicate(true); barracks.zone_type = 201; barracks.owner_allowed = false
	for definition in controller.menu_data.zones:
		if definition.name == "Barracks":
			var observed: Dictionary = definition.duplicate(true); observed.id = 201; controller.zone_types.append(observed)
	controller.use_area(barracks); controller.zone_menu.controls.squads.pressed.emit(); service.poll()
	check(world.calls[-1].candidate_kind == 3 and controller.candidates_view.visible,"squad icon requests native squad candidate list")
	reply(14,{"area":{"list_revision":104,"candidates":[{"id":8,"name":"The Golden Beaks","squad_use":5}]}})
	check(controller.candidates_view.squad_buttons.size() == 4 and not controller.candidates_view.search.visible,"barracks renders four native uses without owner search controls")
	controller.candidates_view.squad_buttons[1].pressed.emit(); service.poll()
	check(world.calls[-1].operation == 12 and world.calls[-1].squad_use == 7,"connected squad toggle retains unrelated use bits")
	barracks.revision += 1; reply(11,{"areas":[barracks]}); service.poll()
	check(controller.stockpile_page == "squads" and controller.candidates_state.area.revision == barracks.revision,"squad result retains selector with authoritative new revision")
	reply(14,{"area":{"list_revision":105,"candidates":[{"id":8,"name":"The Golden Beaks","squad_use":7}]}})
	controller.handle_back()
	var archery: Dictionary = barracks.duplicate(true)
	for definition in controller.zone_types:
		if definition.name == "ArcheryRange": archery.zone_type = definition.id; break
	controller.use_area(archery); controller.zone_menu.controls.squads.pressed.emit(); service.poll()
	reply(14,{"area":{"list_revision":106,"candidates":[{"id":8,"name":"The Golden Beaks","squad_use":2}]}})
	check(controller.candidates_state.squad_mask == 2 and controller.candidates_view.squad_buttons.size() == 1,"archery selector exposes training only")
	controller.candidates_view.squad_buttons[0].pressed.emit()
	var squad_ticket: int = controller.request_ticket; count = world.calls.size()
	controller.handle_back(); service.poll()
	check(world.calls.size() == count and service.result(squad_ticket).get("outcome","") == "not_sent","Back cancels queued squad edit before dispatch")
	controller.zone_menu.controls.location.pressed.emit(); service.poll()
	check(world.calls[-1].operation == 6 and controller.locations_view.visible,"location icon opens native location list")
	var captions: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(ProjectSettings.globalize_path("res://../../../fixtures/areas/native_guild_subtitles.json")))
	check(captions.cases.size() == 276,"Native guild subtitle matrix is complete")
	for entry in captions.cases:
		var subtitle: String = controller.locations_view.row_subtitle({"location_kind":4,"guild_profession":int(entry.profession),"location_tier":int(entry.tier)})
		check(controller.locations_view.fit_line(subtitle,216,true) == entry.subtitle,"Native guild subtitle differs: %s" % entry)
	check(controller.locations_view.row_subtitle({"location_kind":4}) == "","Missing guild metadata does not invent a subtitle")

	reply(9,{"area":{"build_phase":1,"build_total":20,"build_done":1}})
	count = world.calls.size(); controller._process(0.249); service.poll()
	check(world.calls.size() == count,"location builder waits before polling")
	controller._process(0.001); service.poll()
	reply(9,{"area":{"list_revision":107,"build_phase":3,"locations":[{"id":0,"name":"The Oily Meal","location_kind":1,"religion":""}]}})
	controller.locations_view.choices[0].pressed.emit(); service.poll()
	check(world.calls[-1].operation == 7 and world.calls[-1].location_id == 0 and world.calls[-1].expected_revision == archery.revision,"location choice preserves observed zero ID and exact zone revision")
	archery.location_id = 0; archery.location_name = "The Oily Meal"; archery.revision += 1
	reply(11,{"areas":[archery]})
	check(not controller.locations_view.visible and controller.selected.location_id == 0,"confirmed location assignment returns to observed zone")
	controller.zone_menu.controls.location.pressed.emit(); service.poll()
	reply(9,{"area":{"list_revision":108,"locations":[{"id":0,"name":"The Oily Meal","location_kind":1,"religion":""}]}})
	count = world.calls.size()
	controller.locations_view.choices[0].pressed.emit(); service.poll()
	check(world.calls.size()==count and not controller.locations_view.visible and controller.stockpile_page=="types" and controller.selected.location_id==0,"Native same-location selection closes chooser without mutation")
	controller.zone_menu.controls.location.pressed.emit(); service.poll()
	reply(9,{"area":{"list_revision":108,"locations":[]}})
	controller.locations_view.create_buttons[2].pressed.emit(); service.poll()
	check(world.calls[-1] == {"action":11,"id":archery.id,"kind":1,"expected_revision":archery.revision,"operation":8,"location_kind":3},"library creation sends only semantic kind and revision")
	archery.location_id = 11; archery.revision += 1; reply(11,{"areas":[archery]})
	controller.zone_menu.controls.location.pressed.emit(); service.poll()
	reply(9,{"area":{"list_revision":110,"locations":[]}})
	controller.locations_view.create_buttons[1].pressed.emit(); service.poll()
	check(world.calls[-1] == {"action":9,"operation":20,"kind":1,"location_kind":2,"cursor":0},"Temple opens read-only native catalog")
	var temple_rows := [{"kind":1,"id":-1,"name":"","worshippers":0,"has_temple":false,"deities":[]},
		{"kind":2,"id":483,"name":"Synthetic deity","worshippers":1,"has_temple":true,"deities":[{"id":483,"name":"Synthetic deity","spheres":[107]}]}]
	reply(9,{"area":{"location_catalog":{"kind":2,"revision":51,"cursor":0,"total":2,"next_cursor":0,"religions":temple_rows,"guilds":[]}}})
	var selector = controller.locations_view.catalog_view
	check(selector.visible and selector.choices.size() == 2 and not controller.locations_view.body.visible,"Temple selector replaces chooser content")
	selector.choices[1].mouse_entered.emit()
	check(selector.detail.text == "1 worshipper\nThe Sun","hover uses native count and sphere mapping")
	count = world.calls.size(); controller.handle_back(); service.poll()
	check(world.calls.size() == count and controller.locations_view.visible and controller.locations_state.catalog_kind == 0,"selector Back returns to chooser without mutation")
	controller.locations_view.create_buttons[1].pressed.emit(); service.poll()
	reply(9,{"area":{"location_catalog":{"kind":2,"revision":52,"cursor":0,"total":2,"next_cursor":0,"religions":temple_rows,"guilds":[]}}})
	selector.choices[0].pressed.emit(); service.poll()
	check(world.calls[-1] == {"action":11,"id":archery.id,"kind":1,"expected_revision":archery.revision,"operation":8,"location_kind":2,"deity_kind":1,"deity_id":-1},"no-deity choice preserves semantic sentinel and exact area revision")
	archery.location_id = 12; archery.revision += 1; reply(11,{"areas":[archery]})
	controller.zone_menu.controls.location.pressed.emit(); service.poll(); reply(9,{"area":{"list_revision":111,"locations":[]}})
	controller.locations_view.create_buttons[3].pressed.emit(); service.poll()
	check(world.calls[-1].location_kind == 4 and world.calls[-1].operation == 20,"Guildhall opens guild catalog")
	var guild_rows := [{"profession":41,"workers":29,"has_meeting_place":true,"guild_id":1316,"guild_name":"Synthetic guild","members":24}]
	reply(9,{"area":{"location_catalog":{"kind":4,"revision":61,"cursor":0,"total":1,"next_cursor":0,"religions":[],"guilds":guild_rows}}})
	selector.choices[0].mouse_entered.emit()
	check(selector.detail.text == "29 workers\nGuild:\nSynthetic guild\n24 members","guild hover preserves observed membership")
	selector.choices[0].pressed.emit(); service.poll()
	check(world.calls[-1] == {"action":11,"id":archery.id,"kind":1,"expected_revision":archery.revision,"operation":8,"location_kind":4,"profession":41},"Guildhall creation uses observed profession only")
	archery.location_id = 13; archery.revision += 1; reply(11,{"areas":[archery]})
	controller.zone_menu.controls.location.pressed.emit(); service.poll()
	reply(9,{"area":{"list_revision":109,"locations":[]}})
	controller.locations_view.remove.pressed.emit()
	var location_ticket: int = controller.request_ticket; count = world.calls.size()
	controller.handle_back(); service.poll()
	check(world.calls.size() == count and service.result(location_ticket).get("outcome","") == "not_sent","location Cancel retires queued removal without sending")
	for type_name in ["MeetingHall","Office"]:
		var typed: Dictionary = zone.duplicate(true); typed.zone_type = 300 if type_name == "MeetingHall" else 301
		typed.zone_label = "Meeting Area" if type_name == "MeetingHall" else "Office"
		typed.owner_allowed = type_name == "Office"; typed.location_id = 0
		typed.location_name = "The Golden Shrine"; typed.religion = "The Bejeweled Creed"
		typed.location_kind = 2; typed.owner_name = "Observed owner"; typed.owner_profession = "Miner"; typed.owner_sex = 0
		for definition in controller.menu_data.zones:
			if definition.name == type_name:
				var observed: Dictionary = definition.duplicate(true); observed.id = typed.zone_type; controller.zone_types.append(observed)
		controller.use_area(typed)
		check(controller.zone_menu.visible and not controller.kind_picker.visible,"native panel replaces generic controls for " + type_name)
		check(controller.zone_menu.type_label.text == typed.location_name and controller.zone_menu.religion_label.text == typed.religion,"location summary uses observed name and religion")
		check(controller.zone_menu.owner_label.text == "Observed owner, Miner, ♀","zone owner summary uses observed profession and sex")
		check(controller.zone_menu.controls.location_details.visible and controller.zone_menu.controls.location.position.x == 254,"assigned location has native details and shifted assignment slots")
		if type_name == "Office":
			controller.zone_menu.controls.owner.pressed.emit(); service.poll()
			check(controller.candidates_view.visible and world.calls[-1].candidate_kind == 1,"Office opens native owner selector")
			controller.handle_back(); reply(14,{"area":{"list_revision":110,"candidates":[]}})
		typed.location_id = -1; typed.location_name = ""; typed.religion = ""; controller.use_area(typed)
		check(controller.zone_menu.type_label.text == typed.zone_label and not controller.zone_menu.controls.location_details.visible,"unassigned zone restores type summary and single location button")
	controller.inspect_tile(Vector3i(9,9,2)); service.poll(); reply(8,{"areas":[pile],"area_next_cursor":0})
	check(controller.selected.is_empty() and controller.mode == "zone_select" and controller.zone_menu.visible,"empty zone hit clears old selection and restores chooser")
	controller.inspect_tile(Vector3i(3,4,2)); service.poll()
	reply(8,{"areas":[zone],"area_next_cursor":90}); service.poll()
	controller.close_panel()
	reply(8,{"areas":[zone],"area_next_cursor":0})
	check(not controller.panel.visible and controller.selected.is_empty(),"late closed zone lookup cannot restore a selection")
	check(controller.zone_lookup_rows.is_empty() and controller.zone_overlaps.is_empty(),"closed paged lookup retires all retained navigation identities")
	controller.free(); host.free(); service.free(); interaction.free()
	await process_frame
	print("AREA_LINKS PASS" if failures == 0 else "AREA_LINKS FAIL")
	quit(failures)
