extends SceneTree
var failures := 0
func check(value: bool, message: String) -> void:
	if not value: failures += 1; push_error(message)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	var state := preload("res://scripts/area_candidates_state.gd").new()
	var sent: Array = []; state.request_ready.connect(func(request): sent.append(request))
	var area := {"id":82,"kind":1,"revision":9007199254740993,"owner_allowed":true,"owner_id":17}
	state.open(area)
	check(sent[-1] == {"action":14,"operation":14,"id":82,"kind":1,"candidate_kind":1,"query":"","sort":0,"sort_descending":false,"cursor":0},"owner selector uses enriched native candidate request")
	state.accept({"build_phase":1,"build_done":1,"build_total":20},sent[-1])
	state.poll(0.249); check(sent.size() == 1,"pending list is not continuously polled")
	state.poll(0.001); check(sent.size() == 2,"pending builder polls after 250ms")
	state.queue_search("Urist")
	state.accept({"list_revision":7,"candidates":[{"id":17,"name":"Old result"}]},sent[-1])
	check(state.rows.is_empty(),"old query reply cannot replace the newer search")
	state.poll(0.25); check(sent[-1].query == "Urist","latest search starts after obsolete reply retires")
	state.accept({"list_revision":9007199254740993,"build_phase":3,"candidates":[{"id":21,"name":"Urist","profession":"Miner","sex":1,"mood":3}],"next_cursor":1},sent[-1])
	state.more()
	check(sent[-1].cursor == 1 and sent[-1].expected_list_revision == 9007199254740993,"pagination retains exact list receipt")
	state.accept({"list_revision":9007199254740993,"candidates":[{"id":22,"name":"Urist Two"}],"next_cursor":0},sent[-1])
	check(state.rows.size() == 2 and state.rows[0].profession == "Miner","phase3 pages retain observed owner metadata")
	state.assign_owner(999)
	check(not state.mutating,"unobserved owner identity is not submitted")
	state.assign_owner(22)
	check(sent[-1] == {"action":11,"id":82,"kind":1,"expected_revision":9007199254740993,"owner_id":22},"owner edit sends observed identity and exact area revision")
	var count := sent.size(); state.assign_owner(21); state.order(1); state.queue_search("Other")
	check(sent.size() == count and state.area.owner_id == 17,"pending assignment cannot be duplicated or optimistically applied")
	state.clear(); state.accept({"list_revision":8,"candidates":[{"id":99}]},sent[-1])
	check(state.rows.is_empty() and state.area.is_empty(),"closed state rejects late page")
	state.open(area); state.accept({"list_revision":1,"candidates":[],"next_cursor":0},sent[-1])
	state.assign_owner(-1)
	check(sent[-1].owner_id == -1,"remove assignment is available even with empty candidate results")
	state.open(area); state.accept({"build_phase":1,"build_total":20},sent[-1])
	state.order(1); state.poll(0)
	check(sent[-1].sort == 1 and not sent[-1].sort_descending,"sort supersedes waiting builder without polling obsolete order")
	state.accept({"list_revision":3,"candidates":[],"next_cursor":1},sent[-1])
	state.order(1); state.poll(0)
	check(sent[-1].sort_descending,"second sort click reverses direction")
	state.accept({"list_revision":4,"candidates":[],"next_cursor":1},sent[-1]); state.more()
	state.accept({"list_revision":5,"candidates":[{"id":99}]},sent[-1])
	check(state.failed and state.rows.is_empty(),"changed receipt cannot mix candidate snapshots")
	state.clear(); state.open(area); state.accept({"query":"Wrong","list_revision":8},sent[-1])
	check(state.failed,"mismatched page query fails closed")
	state.open(area,2,{"query":"goat","sort":1,"descending":true})
	state.accept({"list_revision":11,"candidates":[{"id":24,"name":"Goat","assigned":false,"grazer":true}]},sent[-1])
	state.toggle_animal(24)
	check(sent[-1] == {"action":11,"operation":11,"kind":1,"id":82,"expected_revision":9007199254740993,"unit_id":24,"assign":1},"animal selection sends isolated native assignment")
	check(not state.rows[0].assigned,"animal checkbox remains observed while mutation pending")
	area.revision += 1; state.open(area,2,{"query":"goat","sort":1,"descending":true})
	check(sent[-1].query == "goat" and sent[-1].sort_descending,"animal refresh retains search and sort")
	state.accept({"list_revision":12,"candidates":[{"id":24,"name":"Goat","assigned":true}]},sent[-1])
	state.toggle_animal(24)
	check(sent[-1].assign == 0 and sent[-1].expected_revision == area.revision,"animal deselection uses refreshed revision")
	state.open(area,3)
	state.accept({"list_revision":13,"candidates":[{"id":8,"name":"Squad","squad_use":5}]},sent[-1])
	state.toggle_squad(8,2)
	check(sent[-1].operation == 12 and sent[-1].squad_id == 8 and sent[-1].squad_use == 7,"training toggle preserves other observed barracks flags")
	state.open(area,3,{"squad_mask":2})
	state.accept({"list_revision":14,"candidates":[{"id":8,"name":"Squad","squad_use":2}]},sent[-1])
	count = sent.size(); state.toggle_squad(8,1)
	check(sent.size() == count,"archery selector cannot submit sleep use")
	state.toggle_squad(8,2)
	check(sent[-1].squad_use == 0,"archery training can be removed")
	var locations := preload("res://scripts/area_locations_state.gd").new()
	locations.request_ready.connect(func(request): sent.append(request))
	locations.open(area)
	locations.accept({"list_revision":9007199254740993,"locations":[{"id":0,"name":"Library"}],"next_cursor":1},sent[-1])
	locations.more()
	check(sent[-1].expected_list_revision == 9007199254740993 and sent[-1].cursor == 1,"location paging carries exact receipt")
	locations.accept({"list_revision":9007199254740993,"locations":[{"id":5,"name":"Tavern"}]},sent[-1])
	check(locations.rows.size() == 2,"location pages accumulate observed identities")
	count = sent.size(); locations.assign(99)
	check(sent.size() == count,"unknown location cannot mutate")
	for kind in [2,4]:
		locations.create(kind)
		check(sent[-1].action == preload("res://scripts/management_contract.gd").ManagementAction.AreaInspect and sent[-1].operation == preload("res://scripts/management_contract.gd").AreaOperation.LocationChoices and sent[-1].location_kind == kind and not locations.mutating,"religion/guild creation first reads authoritative choices")
		count = sent.size(); locations.choose_catalog(0)
		check(sent.size() == count,"unobserved creation choice cannot mutate")
		locations.back_catalog()
	locations.assign(0)
	check(sent[-1].location_id == 0 and sent[-1].expected_revision == area.revision,"zero location identity remains selectable")
	locations.clear(); locations.accept({"list_revision":99,"locations":[{"id":99}]},sent[-1])
	check(locations.rows.is_empty(),"closed location selector ignores late rows")
	locations.open(area); locations.accept({"list_revision":2,"locations":[],"next_cursor":1},sent[-1]); locations.more()
	locations.accept({"list_revision":3,"locations":[{"id":99}]},sent[-1])
	check(locations.failed and locations.rows.is_empty(),"location pages cannot mix list revisions")
	print("AREA_CANDIDATES PASS" if failures == 0 else "AREA_CANDIDATES FAIL")
	quit(failures)
