extends SceneTree
const State = preload("res://scripts/area_settings_state.gd")
const C = preload("res://scripts/management_contract.gd")
var failures := 0
var requests: Array = []
func check(value: bool, description: String) -> void:
	if not value: failures += 1; push_error(description)
func page(state, rows: Array, revision := 9007199254740993, cursor := 0) -> void:
	state.accept({"list_key":state.pending.list_key,"settings":rows,"list_revision":revision,
		"build_phase":3,"build_done":100,"build_total":100,"next_cursor":cursor},state.pending.duplicate(true))
func _initialize() -> void:
	var state := State.new()
	state.request_ready.connect(func(value): requests.append(value))
	state.open({"categories":131071,"id":39,"revision":11})
	page(state,[{"key":"ammo","label":"Ammo","kind":1,"state":1}])
	page(state,[{"key":"ammo/type","label":"Type","kind":2,"state":1},{"key":"ammo/metal","label":"Metal","kind":2,"state":1}])
	check(state.pending.list_key == "ammo/type" and state.pending_column == 2,"Ammo opens native Type through its middle column")
	page(state,[{"key":"ammo/type/0","label":"bolts","kind":4,"state":1}])
	state.select(1,state.rows[1][1])
	check(state.pending.list_key == "ammo/metal" and state.rows[1].size() == 2,"Ammo middle-column navigation preserves native hierarchy")
	page(state,[{"key":"ammo/metal/0","label":"iron","kind":4,"state":1}])
	state.select(2,state.rows[2][0])
	check(requests[-1].list_key == "ammo/metal" and requests[-1].row_key == "ammo/metal/0","Ammo material edit preserves native selector identity")
	state.open({"categories":131071,"id":39,"revision":11})
	page(state,[{"key":"animals","label":"Animals","kind":1,"state":1}])
	page(state,[{"key":"animals/empty_cages","label":"Empty cages","kind":3,"state":1},{"key":"animals/empty_traps","label":"Empty animal traps","kind":3,"state":1}])
	check(state.pending.list_key == "animals/animals" and state.pending_column == 2,"Animals requests the supported creature list beside its boolean options")
	page(state,[{"key":"animals/animals/7","label":"aardvarks","kind":4,"state":1}])
	check(state.rows[1].size() == 2 and state.rows[2].size() == 1 and state.subcategory.is_empty(),"Animals preserves cage options without inventing a middle navigation row")
	state.select(2,state.rows[2][0])
	check(requests[-1].row_key == "animals/animals/7" and requests[-1].expected_revision == 11 and requests[-1].value == 2,"animal leaf edit uses native row identity and area revision")
	state.clear(); requests.clear()
	state.open({"categories":131071,"id":39,"revision":9007199254740995})
	check(requests[-1].expected_revision == 9007199254740995 and requests[-1].operation == 1,"settings read retains exact inspected area revision")
	state.accept({"build_phase":1,"build_done":0,"build_total":100},requests[-1])
	state.poll(0.249); check(requests.size() == 1,"pending summary waits 250ms")
	state.poll(0.001); check(requests.size() == 2 and requests[-1] == requests[0],"summary polling reuses only its read request")
	page(state,[{"key":"wood","label":"Wood","kind":1,"state":3},{"key":"food","label":"Food","kind":1,"state":1}])
	check(state.pending.list_key == "wood","first observed category opens without invented ID")
	page(state,[{"key":"wood/0","label":"Oak","kind":4,"state":1}],9007199254740993,128)
	check(state.rows[1].is_empty() and state.rows[2].size() == 1 and state.leaf == "wood","direct Wood leaves occupy third column")
	state.more(2)
	check(requests[-1].cursor == 128 and requests[-1].expected_list_revision == 9007199254740993,"scroll paging echoes exact list revision")
	page(state,[{"key":"wood/9","label":"Pine","kind":4,"state":2}])
	check(state.rows[2].size() == 2,"later page appends in observed order")
	state.open({"categories":131071,"id":39,"revision":9007199254740995},true)
	check(state.rows[2].size() == 2,"refresh retains old disabled rows instead of collapsing scroll extent")
	page(state,[{"key":"wood","label":"Wood","kind":1,"state":3},{"key":"food","label":"Food","kind":1,"state":1}])
	page(state,[{"key":"wood/0","label":"Oak","kind":4,"state":1}],9007199254740997,128)
	check(state.rows[2].size() == 2 and state.pending.cursor == 128 and state.pending.expected_list_revision == 9007199254740997,"refresh restores loaded depth using the new receipt before publishing")
	page(state,[{"key":"wood/9","label":"Pine","kind":4,"state":2}],9007199254740997)
	check(not state.busy() and not state.refreshing and state.rows[2].size() == 2,"refreshed pages publish together at prior depth")
	state.select(2,state.rows[2][0])
	check(requests[-1].operation == 2 and requests[-1].scope == 1 and requests[-1].row_key == "wood/0" and requests[-1].value == 2,"leaf click enables the observed off row")
	var count := requests.size(); state.edit(0,4,1)
	check(requests.size() == count and state.rows[2][0].state == 1,"pending write prevents duplicates and optimistic state")
	state.open({"categories":131071,"id":39,"revision":9007199254740997},true)
	page(state,[{"key":"wood","label":"Wood","kind":1,"state":2},{"key":"food","label":"Food","kind":1,"state":1}])
	page(state,[{"key":"wood/0","label":"Oak","kind":4,"state":2}])
	state.search("oak")
	check(requests[-1].query == "OAK" and requests[-1].cursor == 0 and not requests[-1].has("expected_list_revision"),"new search starts a fresh filtered receipt")
	page(state,[{"key":"wood/0","label":"Oak","kind":4,"state":2}])
	count = requests.size(); state.edit(2,2,1)
	check(requests.size() == count+1 and requests[-1].scope == 2 and requests[-1].query == "OAK" and requests[-1].expected_revision == 9007199254740997,"filtered All/None carries query and exact area revision")
	state.mutating = false
	state.area.categories = 2
	state.select(0,state.rows[0][1])
	page(state,[{"key":"food/meat","label":"Meat","kind":2,"state":3},{"key":"food/prepared_meals","label":"Prepared meals","kind":3,"state":1}])
	check(state.pending.list_key == "food/meat" and state.pending.query == "OAK","category navigation preserves native search")
	page(state,[])
	check(not state.busy() and state.rows[2].is_empty(),"completed empty leaf list is ready")
	state.edit(1,1,2,"food/prepared_meals")
	check(requests[-1].list_key == "food" and requests[-1].row_key == "food/prepared_meals","middle toggle uses parent list and semantic row key")
	state.reject(); count = requests.size(); state.edit(0,4,2)
	check(requests.size() == count and state.failed,"rejected edit requires refresh; never replays")
	state.clear(); state.poll(1)
	check(state.area.is_empty() and state.rows == [[],[],[]] and requests.size() == count,"close clears pages and polling")
	state.open({"categories":131071,"id":39,"revision":100})
	page(state,[{"key":"wood","label":"Wood","kind":1,"state":1}])
	page(state,[{"key":"wood/0","label":"Oak","kind":4,"state":1}],10,128)
	state.more(2)
	page(state,[{"key":"wood/1","label":"Pine","kind":4,"state":2}],11)
	check(state.failed and state.rows[2].size() == 1,"changed list receipt rejects appended page without mixing states")
	state.open({"categories":131071,"id":39,"revision":100})
	page(state,[{"key":"wood","label":"Wood","kind":1,"state":1}])
	page(state,[{"key":"wood/0","label":"Oak","kind":4,"state":1}])
	count = requests.size()
	state.queue_search("o"); state.poll(0.2); state.queue_search("oak"); state.poll(0.249)
	check(requests.size() == count and state.busy(),"typing coalesces reads and disables stale row edits")
	state.poll(0.001)
	check(requests.size() == count+1 and requests[-1].query == "OAK","latest draft dispatches after 250ms")
	var obsolete: Dictionary = requests[-1].duplicate(true)
	state.queue_search("pine")
	state.accept({"list_revision":12,"list_key":"wood","query":"OAK","settings":[{"key":"wood/0","label":"Oak","kind":4,"state":1}]},obsolete)
	check(state.rows[2].is_empty() and state.pending.is_empty(),"late old-search rows never populate a newer query")
	state.poll(0.25)
	check(requests[-1].query == "PINE","new query follows terminal obsolete read without replaying it")
	state.accept({"build_phase":1,"build_done":0,"build_total":100},requests[-1])
	count = requests.size(); state.queue_search("birch"); state.poll(0.25)
	check(requests.size() == count+1 and requests[-1].query == "BIRCH","new search replaces obsolete builder poll without another old request")
	state.clear(); count = requests.size(); state.poll(1)
	check(requests.size() == count,"closing cancels pending search and builder reads")
	state.open({"id":39,"revision":101,"categories":8256})
	page(state,[{"key":"wood","kind":1,"state":1},{"key":"food","kind":1,"state":1}])
	page(state,[])
	state.select(0,state.rows[0][1])
	check(state.mutating and requests[-1].action == C.ManagementAction.AreaUpdate and requests[-1].operation == 0 and requests[-1].changed_categories == 2 and requests[-1].categories == 2 and requests[-1].expected_revision == 101,"disabled category selection enables only its flag through an explicit guarded write")
	count = requests.size(); state.select(0,state.rows[0][0]); state.poll(2)
	check(requests.size() == count,"category activation cannot duplicate or poll while pending")
	state.reject(); state.poll(2)
	check(requests.size() == count and state.failed,"failed category activation is never replayed")
	state.open({"id":39,"revision":102,"categories":8258},true)
	page(state,[{"key":"food","kind":1,"state":1}]); page(state,[])
	state.select(0,state.rows[0][0])
	check(requests[-1].action == C.ManagementAction.AreaInspect,"already enabled category selection only reads")
	state.open({"id":39,"revision":103,"categories":0})
	check(state.mutating and requests[-1].action == C.ManagementAction.AreaUpdate and requests[-1].changed_categories == 64 and requests[-1].categories == 64 and requests[-1].expected_revision == 103,"initial Custom enables only Ammo before reading settings")
	state.reject(); count = requests.size(); state.poll(2)
	check(state.failed and requests.size() == count,"initial activation rejection never replays")
	state.open({"id":39,"revision":104,"categories":0},true)
	page(state,[{"key":"ammo","kind":1,"state":1}])
	check(requests[-1].action == C.ManagementAction.AreaInspect and not state.mutating,"background refresh does not activate an externally disabled category")
	print("AREA_SETTINGS PASS" if failures == 0 else "AREA_SETTINGS FAIL")
	quit(failures)
