extends SceneTree

func _initialize(): call_deferred("run")

func run():
	var world := Df3dWorld.new()
	root.add_child(world)
	world.set_fixed_render_tick(10)
	assert(world.load_fixture(ProjectSettings.globalize_path("res://../../../build/interaction.df3dfix")))
	world.poll()
	var markers: Array = world.designation_tiles(1)
	assert(markers.size() == 4)
	var before := world.auxiliary_cache_stats()
	assert(world.designation_tiles(1) == markers)
	var after := world.auxiliary_cache_stats()
	assert(after.designation_builds == before.designation_builds)
	assert(after.designation_tile_samples == before.designation_tile_samples)
	assert(after.designation_cache_hits == before.designation_cache_hits + 1)
	# Returned dictionaries remain caller-owned; edits cannot poison cached orders.
	markers[0].kind = 99
	assert(world.designation_tiles(1)[0].kind != 99)
	assert(world.designation_tiles(-1).is_empty())
	assert(world.designation_tiles(2).size() == 1)
	assert(world.designation_tiles(1).size() == 4)
	world.set_reveal_hidden(true)
	var hidden: Array = world.designation_tiles(1).filter(func(d): return d.tile == Vector3i(5,2,1))
	assert(hidden.size() == 1 and hidden[0].height == 1.0)
	# Licensed lane additionally exercises texture reuse, sampling and scope.
	if OS.get_environment("DF3D_DF_PATH") != "":
		assert(world.load_assets(OS.get_environment("DF3D_DF_PATH")))
		var data := world.minimap_data(1,32)
		assert(data.available)
		before = world.auxiliary_cache_stats()
		assert(world.minimap_data(1,32).texture == data.texture)
		after = world.auxiliary_cache_stats()
		assert(after.minimap_tile_samples == before.minimap_tile_samples)
		assert(after.minimap_builds == before.minimap_builds)
		world.minimap_data(2,32)
		assert(world.auxiliary_cache_stats().minimap_evaluations == before.minimap_evaluations + 1)
		assert(not world.minimap_data(-1,32).available)
		assert(world.minimap_data(1,32).available)
	before = world.auxiliary_cache_stats()
	assert(world.load_fixture(ProjectSettings.globalize_path("res://../../../build/interaction.df3dfix")))
	world.poll()
	assert(world.designation_tiles(1).size() == 4)
	assert(world.auxiliary_cache_stats().designation_builds == before.designation_builds + 1)
	world.free()
	print("AUXILIARY_CACHE_PASS")
	quit()
