extends SceneTree
const Effects = preload("res://scripts/combat_effects.gd")
var failures := 0
func check(ok: bool, message: String):
	if not ok: failures += 1; push_error(message)
func _initialize(): call_deferred("run")
func run():
	var effects := Effects.new()
	root.add_child(effects)
	effects.configure(OS.get_environment("DF3D_DF_PATH"))
	check(effects.effects.size() >= 72, "Native outcome and mining directions parsed")
	check(effects.materials.size() == 4, "Native sheets resident")
	check(effects.direction(Vector3.RIGHT) == "E" and effects.direction(Vector3.FORWARD) == "N", "Directions follow DF tile axes")
	for outcome in ["HIT", "MISS", "BLOCK", "PARRY"]:
		check(effects.emit_effect(outcome, Vector3.ZERO, Vector3.RIGHT, 1.0), "Native outcome available: " + outcome)
	check(effects._pool[0].get_instance_shader_parameter("world_direction") == Vector2.LEFT, "West attacker uses west side of target, not eastward travel")
	var id: int = effects._pool[0].mesh.get_instance_id()
	effects.set_style(true)
	effects.set_style(false)
	check(effects._pool[0].mesh.get_instance_id() == id, "Style changes keep resident geometry")
	for i in 40: effects.emit_effect("HIT", Vector3.ZERO, Vector3.RIGHT, 1.0)
	check(effects.counters.spawned == 32 and effects.counters.dropped > 0, "Transient budget bounded")
	effects.advance(1.1)
	check(effects._pool[0].visible, "Effect alive at presentation clock")
	effects.advance(1.3)
	check(effects._pool.all(func(piece): return not piece.visible), "Expired effects hidden")
	check(not effects.emit_effect("HIT", Vector3.ZERO, Vector3.ZERO, 2.0), "Unknown direction does not invent target")
	check(not effects.emit_effect("HIT", Vector3.ZERO, Vector3.UP, 2.0), "Vertical-only direction has no planar atlas row")
	effects.emit_effect("HIT", Vector3.ZERO, Vector3.RIGHT, 2.0)
	effects.reset_session()
	check(effects._pool.all(func(piece): return not piece.visible), "Session reset clears effects")
	effects.free()
	print("COMBAT_EFFECTS_TEST_PASS" if failures == 0 else "COMBAT_EFFECTS_TEST_FAIL")
	quit(0 if failures == 0 else 1)
