extends SceneTree
# Real fixture -> presentation revisions -> actual MultiMeshes. No native game
# or installed art is needed: unresolved pieces exercise the same upload guard.
var failures: Array[String] = []
class IsolatedView:
	extends "res://scripts/world_view.gd"
	# Exercise actual upload methods without asset discovery, live connections,
	# or the application's UI/audio setup. Required collaborators are explicit.
	func _ready(): pass
	func _process(_delta: float): pass

func check(value: bool, message: String):
	if not value: failures.append(message)

func mesh_node() -> MultiMeshInstance3D:
	var node := MultiMeshInstance3D.new()
	var mm := MultiMesh.new()
	mm.transform_format = MultiMesh.TRANSFORM_3D
	mm.use_colors = true
	mm.use_custom_data = true
	mm.mesh = BoxMesh.new()
	node.multimesh = mm
	return node

func _initialize():
	call_deferred("run")

func run():
	var world := Df3dWorld.new()
	var view := IsolatedView.new()
	world.name = "Df3dWorld"
	view.add_child(world)
	for pair in [["Units", mesh_node()], ["ItemMarkers", mesh_node()], ["Terrain", Node3D.new()], ["Buildings", Node3D.new()]]:
		pair[1].name = pair[0]
		view.add_child(pair[1])
	var rig := Node3D.new(); rig.name = "CameraRig"
	var camera := Camera3D.new(); camera.name = "Camera3D"
	rig.add_child(camera); view.add_child(rig)
	var ui := Node.new(); ui.name = "UI"
	var status := Label.new(); status.name = "Status"
	ui.add_child(status); view.add_child(ui)
	view.add_child(view._projectiles); view.add_child(view._unit_status)
	view._sprite_presentation = preload("res://scripts/sprite_presentation.gd").new()
	view.add_child(view._sprite_presentation)
	view._gameplay_feedback = preload("res://scripts/gameplay_feedback.gd").new()
	view._gameplay_feedback.world = world
	view._unit_status.world = world
	view._unit_status.motion = view._actor_motion
	view._unit_demand.enabled = false
	root.add_child(view)
	view._sprite_presentation.configure(view)
	# Generated by make_interaction_fixture: no appearance stacks. The demo
	# intentionally keeps composites pending without assets and cannot idle.
	world.set_fixed_render_tick(10)
	check(world.load_fixture(ProjectSettings.globalize_path("res://../../../build/interaction.df3dfix")), "fixture loads")
	world.poll()
	view._update_units()
	view._update_items()
	check(world.unit_count() > 0 and world.item_positions().size() > 0, "fixture supplies real pieces")
	# The first item manifest establishes native group ownership and advances its
	# revision. Settle that cold baseline before measuring unchanged frames.
	world.poll()
	view._update_units()
	view._update_items()
	var unit_revision := world.unit_render_revision()
	var item_revision := world.item_render_revision()
	var uploads := Vector2i(view._unit_upload_count, view._item_upload_count)
	var resizes: int = view._instance_resize_count
	for i in 12:
		world.poll()
		view._update_units()
		view._update_items()
	check(world.unit_render_revision() == unit_revision and world.item_render_revision() == item_revision, "frozen poll retains independent revisions")
	check(Vector2i(view._unit_upload_count, view._item_upload_count) == uploads, "frozen pieces do not upload")
	check(view._instance_resize_count == resizes, "frozen pieces do not resize buffers")
	world.set_fixed_render_tick(10.25)
	world.poll()
	view._update_units()
	view._update_items()
	check(world.unit_render_revision() == unit_revision and view._unit_upload_count == uploads.x, "fractional interpolation reuses resident motion intervals without unit uploads")
	check(world.item_render_revision() == item_revision and view._item_upload_count == uploads.y, "animation alone does not upload static items")
	check(view._instance_resize_count == resizes, "animation retains matching buffer counts")
	var retained := Transform3D(Basis.IDENTITY, Vector3(3,4,5))
	var mm: MultiMesh = view.units.multimesh
	view._set_instance_count(mm, 1)
	mm.set_instance_transform(0, retained)
	resizes = view._instance_resize_count
	view._set_instance_count(mm, 1)
	check(view._instance_resize_count == resizes, "matching count does not reallocate transform storage")
	# Headless DummyRenderingDevice does not retain GPU transform buffers.
	if DisplayServer.get_name() != "headless":
		check(mm.get_instance_transform(0) == retained, "matching count preserves existing transform")
	world.set_top_z(0)
	world.set_window_depth(1)
	world.poll()
	view._update_units()
	view._update_items()
	check(world.item_render_revision() > item_revision, "slice invalidates item arrays")
	check(view.ItemCapacity.visible_count(view.item_markers.multimesh) == world.item_positions().size(), "slice removes stale visible item instances while retaining capacity")
	check(view.units.multimesh.instance_count == world.unit_cutout_positions().size(), "slice removes stale unit instances")
	# An old textured group must disappear when the next revision omits it.
	var stale := mesh_node()
	stale.multimesh.instance_count = 1
	view.add_child(stale)
	view._item_layers["obsolete"] = stale
	view._sprite_resources.track(stale, 999, "obsolete-art")
	view._cutout_resources["obsolete-art"] = [stale.multimesh.mesh, StandardMaterial3D.new()]
	var group = preload("res://scripts/item_preparation.gd").Group.new()
	group.key = 999; group.layer_key = "obsolete"
	view._item_preparation.groups[999] = group
	var stale_mm: WeakRef = weakref(stale.multimesh)
	view._instance_uploads.begin(stale.multimesh)
	view._item_storage._resident[stale.multimesh.get_instance_id()] = {"owner": group, "version": 0}
	view._item_preparation.source_revision = -1
	view._item_preparation.delta_revision = -1
	view._update_items()
	check(not view._item_layers.has("obsolete") and not view._item_preparation.groups.has(999), "full source manifest retires removed logical and physical groups")
	check(stale_mm.get_ref() == null and not view._cutout_resources.has("obsolete-art"), "retired groups release actual MultiMesh and shared art ownership")
	view.queue_free()
	await process_frame
	await process_frame
	for failure in failures: push_error(failure)
	print("ENTITY_UPLOAD_TEST_PASS" if failures.is_empty() else "ENTITY_UPLOAD_TEST_FAIL")
	quit(0 if failures.is_empty() else 1)
