extends SceneTree
var failures: Array = []
func check(value: bool, message: String):
	if not value: failures.append(message); push_error(message)
func _initialize(): call_deferred("run")
func run():
	var world = Df3dWorld.new()
	root.add_child(world)
	world.set_replay_speed(0)
	check(world.load_fixture(ProjectSettings.globalize_path("res://../../../build/item-updates.df3dfix")), "fixture loads")
	world.poll()
	world.set_top_z(2)
	world.poll()
	var recorder = load("res://scripts/frame_costs.gd").new()
	recorder.configure(world)
	var expected := OS.get_environment("DF3D_PROFILE")
	check(recorder.mode == expected, "script mode matches explicit configuration")
	check(is_instance_valid(recorder._lifecycle) == (expected == "deep"), "lifecycle hooks exist only in deep mode")
	var stats: Dictionary = world.presentation_perf_stats()
	check(stats.profiling_mode == expected, "native mode matches script")
	var submissions: Dictionary = world.engine_submission_stats()
	check(submissions.is_empty() == (expected != "deep"), "engine input counters only in deep mode")
	var detail: Dictionary = world.engine_submission_details()
	var detail_expected := expected == "deep" and OS.get_environment("DF3D_SUBMISSION_DETAIL") == "1"
	check(detail.enabled == detail_expected, "detailed mesh comparisons require deep plus explicit flag")
	if not detail_expected:
		check(detail.buildings.is_empty() and detail.batches.is_empty(), "disabled detail retains no owner events")
	var drained: Dictionary = world.engine_submission_details()
	check(drained.buildings.is_empty() and drained.batches.is_empty(), "detail getter drains owner events")
	if expected == "deep":
		check(submissions.mesh_surface_calls > 0 and submissions.mesh_payload_bytes > 0, "fixture emits measured mesh payload")
		check(submissions.mesh_unknown_channels == 0, "all submitted channels accounted")
	if expected == "off":
		check(recorder.start() == 0 and recorder.mark("ignored", 1) == 0, "disabled timestamps return zero")
		recorder.record("ignored", 1, 1)
		check(recorder.summary().stages.is_empty(), "off retains no samples")
		check(stats.poll_ms == 0.0 and stats.unit_evaluation_ms == 0.0, "off native timers remain zero")
		check(world.profiling_trace().traceEvents.is_empty(), "off native trace stays empty")
		check(recorder.write_capture(world) == "", "off never exports")
	else:
		check(stats.poll_ms > 0.0, "enabled native stages measured")
		var begin: int = recorder.start()
		recorder.mark("test.scope", begin)
		check(recorder.summary().stages.has("test.scope"), "basic scope recorded")
		check((recorder.start(true) != 0) == (expected == "deep"), "deep-only clocks are gated")
		var path: String = recorder.write_capture(world)
		check(not path.is_empty() and FileAccess.file_exists(path), "summary exported")
		var data = JSON.parse_string(FileAccess.get_file_as_string(path))
		check(data.mode == expected and data.native.profiling_mode == expected, "summary identifies configuration")
		var trace: Dictionary = world.profiling_trace()
		check(trace.traceEvents.is_empty() == (expected != "deep"), "native trace only in deep mode")
		if expected == "deep":
			var timeline = JSON.parse_string(FileAccess.get_file_as_string(path.replace(".profile.json", ".trace.json")))
			check(timeline.traceEvents.any(func(event): return event.cat == "script"), "combined timeline contains script")
			check(timeline.traceEvents.any(func(event): return event.cat == "native"), "combined timeline contains native")
		var bounded = load("res://scripts/frame_costs.gd").new()
		var old: Dictionary = bounded.cursor()
		for i in 33000: bounded.record("bounded", i + 1, i)
		check(bounded.since(old).bounded.size() == 4096, "old cursor clips to retained ring")
		check(bounded.since(old).bounded.front() == (33000 - 4096) / 1000.0, "ring retains chronological tail")
		check(bounded.summary().stages.bounded.count == 33000, "aggregates outlive ring eviction")
		check(bounded.summary().stages.bounded.recent_p50_ms > 28.0, "percentiles describe retained samples")
		if expected == "deep":
			check(bounded.summary().retained_events == 32768 and bounded.summary().dropped_events == 232, "deep overflow bounded and counted")
		for i in 70: bounded.record("stage_" + str(i), 1, 1)
		check(bounded.summary().stages.size() == 64 and bounded.summary().dropped_stage_samples > 0, "stage cardinality bounded")
	world.free()
	print("PROFILING_MODE_PASS " + expected if failures.is_empty() else "PROFILING_MODE_FAIL")
	quit(0 if failures.is_empty() else 1)
