extends SceneTree
var failures: Array=[]
var bounds=AABB(Vector3(2.1,0.1,2.1),Vector3(0.8,2.5,0.8))
func check(value: bool, message: String):
 if not value: failures.append(message); push_error(message)
func _initialize(): call_deferred("run")
func advance(world, index: int):
 world.set_replay_elapsed(float(index)*10.0+.001)
 world.poll()
 check(world.bridge_tick()==100+index,"exact roof replay frame "+str(index))
func run():
 var world=Df3dWorld.new()
 root.add_child(world)
 world.set_replay_speed(0)
 var fixture=ProjectSettings.globalize_path("res://../../../build/render-cache.df3dfix")
 check(world.load_fixture(fixture),"roof lifecycle fixture loads")
 world.set_replay_elapsed(0)
 world.poll()
 world.set_top_z(2)
 world.set_window_depth(3)
 world.poll()
 var revision=world.sprite_ceiling_source_revision(bounds,0)
 check(world.sprite_ceiling(bounds,0)>1000,"initial open roof")
 var cached=world.sprite_ceiling_cache_stats()
 for i in 20:
  check(world.sprite_ceiling_source_revision(bounds,0)==revision,"animation-independent local token")
  world.sprite_ceiling(bounds,0)
 check(world.sprite_ceiling_cache_stats().tile_samples==cached.tile_samples,"cached bounds never resample terrain during animation/idle")
 advance(world,1)
 check(world.sprite_ceiling_source_revision(bounds,0)==revision,"water/material changes do not invalidate clipping")
 advance(world,2)
 # Query before revision refresh must NOT overwrite the old occupancy baseline.
 check(is_equal_approx(world.sprite_ceiling(bounds,0),1.994),"new upper roof clips")
 check(world.sprite_ceiling_source_revision(bounds,0)>revision,"local token still records change after an early plane query")
 revision=world.sprite_ceiling_source_revision(bounds,0)
 advance(world,3)
 check(world.sprite_ceiling_source_revision(bounds,0)==revision,"same roof with different water/material remains cached")
 advance(world,4)
 check(world.sprite_ceiling_source_revision(bounds,0)>revision,"lower roof insertion invalidates")
 check(is_equal_approx(world.sprite_ceiling(bounds,0),0.994),"lower roof controls clipping")
 revision=world.sprite_ceiling_source_revision(bounds,0)
 advance(world,5)
 check(world.sprite_ceiling_source_revision(bounds,0)==revision,"solid floor to wall does not change roof occupancy")
 advance(world,6)
 check(world.sprite_ceiling_source_revision(bounds,0)>revision,"removing previously blocking cells invalidates")
 check(world.sprite_ceiling(bounds,0)>1000,"removed roof opens sky")
 revision=world.sprite_ceiling_source_revision(bounds,0)
 advance(world,7)
 check(world.sprite_ceiling_source_revision(bounds,0)>revision,"hidden knowledge becomes conservative solid")
 check(is_equal_approx(world.sprite_ceiling(bounds,0),0.994),"hidden empty cell clips without revealing shape")
 revision=world.sprite_ceiling_source_revision(bounds,0)
 advance(world,8)
 check(world.sprite_ceiling_source_revision(bounds,0)>revision,"revealed open roof invalidates")
 check(world.sprite_ceiling(bounds,0)>1000,"revealed empty is open")
 revision=world.sprite_ceiling_source_revision(bounds,0)
 advance(world,9)
 check(world.sprite_ceiling_source_revision(bounds,0)==revision,"unqueried distant wall change leaves clipping cached")
 world.set_top_z(0)
 check(world.sprite_ceiling_source_revision(bounds,0)>revision,"slice invalidates query scope")
 revision=world.sprite_ceiling_source_revision(bounds,0)
 check(world.load_fixture(fixture),"replacement fixture loads")
 world.poll()
 check(world.sprite_ceiling_source_revision(bounds,0)>revision,"session reload cannot reuse stale revision")
 world.free()
 print("SPRITE_CEILING_REVISION_PASS" if failures.is_empty() else "SPRITE_CEILING_REVISION_FAIL")
 quit(0 if failures.is_empty() else 1)
