"""Generate neutral model enums and Godot names from the existing wire vocabulary.
Run with --check in builds; edit mirror.fbs, then regenerate deliberately.
"""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
ENUMS = ("ManagementAction", "ManagementStatus", "AreaKind", "AlertOperation", "AlertView",
         "SelectionOperation", "SelectionKind", "SelectionSection", "CreatureSectionKind")

def outputs():
    source = (ROOT / "schema/mirror.fbs").read_text()
    values = {}
    for name in ENUMS:
        body = re.search(r"enum " + name + r"\s*:\s*uint8\s*\{([^}]+)\}", source).group(1)
        rows, value = [], 0
        for entry in body.split(","):
            parts = entry.strip().split("=")
            if len(parts) == 2: value = int(parts[1].strip(), 0)
            rows.append((parts[0].strip(), value)); value += 1
        values[name] = rows
    cpp = "// Generated by tools/generate_management_contract.py. Do not edit.\n#pragma once\n#include <cstdint>\nnamespace wm {\n"
    checks = "// Generated exhaustive model/wire correspondence checks.\n"
    gd = "# Generated by tools/generate_management_contract.py. Do not edit.\nextends RefCounted\n"
    for name, rows in values.items():
        cpp += "enum class " + name + " : uint8_t {\n" + "".join(f"  {n} = {v},\n" for n,v in rows) + "};\n"
        gd += "enum " + name + " {\n" + "".join(f"\t{n} = {v},\n" for n,v in rows) + "}\n"
        checks += "".join(f"static_assert(static_cast<int>(wm::{name}::{n}) == static_cast<int>(df3d::mirror::{name}::{n}));\n" for n,v in rows)
        checks += f"static_assert(sizeof(df3d::mirror::EnumValues{name}()) / sizeof(df3d::mirror::{name}) == {len(rows)});\n"
    cpp += "} // namespace wm\n"
    # Semantic mutation policy is centralized here and emitted with named values.
    mutations=("Place","Remove","RemoveConstruction","AreaCreate","AreaUpdate","AreaDelete","AreaLink",
        "ProductionQueue","ProductionJobEdit","FarmSetCrop","WorkOrderCreate","WorkOrderUpdate",
        "WorkOrderDelete","WorkOrderCondition","WorkDetailMembership","WorkDetailMode","TradeUpdate","TradeBring")
    assert set(mutations) <= {n for n,v in values["ManagementAction"]}
    gd += "\nstatic func is_mutation(action: int) -> bool:\n\treturn action in [" + ", ".join("ManagementAction."+n for n in mutations) + "]\n"

    return {"worldmodel/include/wm/management_enums.h":cpp,
            "worldmodel/src/management_enum_checks.inc":checks,
            "presentations/godot/project/scripts/management_contract.gd":gd}

def main():
    parser=argparse.ArgumentParser();parser.add_argument("--check",action="store_true");args=parser.parse_args()
    for name, content in outputs().items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_text()!=content: raise SystemExit(f"Stale management contract: {name}; run tools/generate_management_contract.py")
        else: path.write_text(content)
    print("MANAGEMENT_CONTRACT_GENERATION_PASS")
if __name__=="__main__": main()
