#include "doctest.h"
#include "../bridge/plugin/appearance_color.h"

TEST_CASE("Native tissue replacement follows captured age boundaries") {
    // Native4338, current106/157249. Each pair is retained verbatim from
    // native_location_staff_candidate_aging.json, not generated by the helper.
    struct Sample { int year, tick, start, end; bool active; };
    const Sample samples[] = {
        {51,157249,13440,23520,false}, //55
        {51,153217,13440,23520,false}, //55.01
        {51,36289,13440,23520,false},  //55.30
        {51,32257,13440,23520,true},   //55.31
        {26,116930,23520,30240,false}, //80.1
        {26,76609,23520,30240,true},   //80.2
        {26,72578,23520,30240,true},   //80.21
    };
    for (const auto& s:samples) {
        const double days=df3d_appearance::nativeAgeDays(106,157249,s.year,s.tick);
        CHECK(df3d_appearance::nativeColorModifierActive(s.start,s.end,days)==s.active);
    }
}
